[".tmux"]
  type = "archive"
  url = "https://github.com/gpakosz/.tmux/archive/master.tar.gz" 
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/kitty/kitty.d/onehalfdark.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/sonph/onehalf/master/kitty/onehalf-dark.conf"
    refreshPeriod = "168h"
