[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'sudo.vim'

[[plugins]]
repo = 'kana/vim-fakeclip.git'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'xolox/vim-session'
depends = ['xolox/vim-misc']

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'Align'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# colorscheme
[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  source ~/dotfiles/vimrc-solarized
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/dotfiles/vimrc-lightline
'''
depends = ['altercation/vim-colors-solarized']

# Syntax highlight
[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'timcharper/textile.vim'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
