[tools]
# coding agents
codex = "latest"
gemini = "latest"
opencode = "latest"
claude-code = { version = "latest", install_before = "0d" }
pi = "latest"

# tools
"npm:ccusage" = "latest"

# deployment tools
wrangler = "latest"
